"""added image_filename to product

Revision ID: 7338262c9022
Revises:
Create Date: 2026-07-07 22:20:03.426615

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7338262c9022'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products', sa.Column('image_filename', sa.String(length=120), nullable=True)
    )
    op.alter_column(
        'users', 'username', existing_type=sa.VARCHAR(length=120), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'username', existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.drop_column('products', 'image_filename')
    # ### end Alembic commands ###
